import math

print('CALCULADORA MULTI FUNÇÕES DO BERENARANDO')
print('')
print('======================================================================================')
print('OPERAÇÕES:')
print('')
print('digite 1 pra soma')
print('')
print('digite 2 para subtração')
print('')
print('digite 3 para multiplicação')
print('')
print('digite 4 para divisão')
print('')
print('digite 5 para achar a raiz quadrada de algum numero')
print('')
print('digite 6 para potencialização')
print('')
print('digite 7 para realizar bhaskara')
print('')
comec = input('digite a operação desejada para começar: ')
if comec == '1':
    num1 = float(input('digite o primeiro numero'))
    print('')
    num2 = float(input('digite o segundo numero'))
    print('')
    num3 = float(input('digite o terceiro numero'))
    print('')
    resultado = (num1 + num2 + num3)
    print('o resultado é de: ', resultado)
elif comec == '2':
    print('para que o resultado não seja negativo coloque o maior numero primeiro')
    print('')
    num1 = float(input('digite o primeiro numero'))
    print('')
    num2 = float(input('digite o segundo numero'))
    print('')
    resultado = (num1 - num2)
    print('o resultado é de: ', resultado)
elif comec == '3':
    num1 = float(input('digite o primeiro numero'))
    print('')
    num2 = float(input('digite o segundo numero'))
    print('')
    resultado = (num1 * num2)
    print('o resultado é de: ', resultado)
elif comec == '4':
    num1 = float(input('digite o primeiro numero'))
    print('')
    num2 = float(input('digite o segundo numero'))
    print('')
    resultado = (num1 / num2)
    print('o resultado é de: ', resultado)
elif comec == '5':
    num1 = float(input('digite o numero que voce deseja achar a raiz quadrada: '))
    resultado = math.sqrt(num1)
elif comec == '6':
    num1 = float(input('digite o numero a ser potencializado: '))
    print('')
    pot = float(input('digite a potencia'))
    resultado = (num1 ** pot)
    print('')
    print('o resultado é de: ', resultado)
elif comec == '7':
    a = float(input('Digite o valor de A: '))
    print('')
    b = float(input('Digite o valor de B: '))
    print('')
    c = float(input('Digite o valor de C: '))
    print('')
    delta = (b * b - 4 * a * c)
    if delta < 0:
        print("\"não\" possuem resultados reais para esta operação")
    elif delta == 0:
        x = - b / (2 * a)
        print('Tanto x quanto x² são ', x)
    if delta > 0:
        print('o valor de delta é de: ', delta)
        r1 = (-b + (math.sqrt(delta))) / (2 * a)
        r2 = (-b - (math.sqrt(delta))) / (2 * a)
        print("o resultado final é de: x¹ ={} e x² = {} ".format(r1, r2))
else:
    print('operação inexistente')
